services:  # Define los servicios que Docker Compose gestionará.

  app:  # Nombre del servicio para la aplicación.
  
    build: .  # Indica que Docker Compose debe construir la imagen Docker utilizando el Dockerfile en el directorio actual.
    
    ports:  # Configura el mapeo de puertos entre el contenedor y tu máquina local.
      - "3001:3001"  # Mapea el puerto 3001 del contenedor al puerto 3001 de tu máquina local, permitiendo el acceso a la aplicación.

    environment:  # Define variables de entorno que se pasarán al contenedor cuando se ejecute.
      - NODE_ENV=production  # Configura la variable de entorno 'NODE_ENV' como 'production'. Esto indica que la aplicación se ejecutará en modo producción.

  prometheus:  # Nombre del servicio para Prometheus.
  
    image: prom/prometheus  # Especifica la imagen Docker que se usará para el servicio Prometheus (de la imagen oficial de Prometheus en Docker Hub).

    volumes:  # Define volúmenes para montar archivos o directorios del host en el contenedor.
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Monta el archivo 'prometheus.yml' desde el directorio actual al contenedor en la ruta '/etc/prometheus/prometheus.yml'. Prometheus lo usará como su archivo de configuración.

    ports:  # Configura el mapeo de puertos para Prometheus.
      - "9090:9090"  # Mapea el puerto 9090 del contenedor (donde Prometheus expone su interfaz) al puerto 9090 de tu máquina local.

  grafana:  # Nombre del servicio para Grafana.
  
    image: grafana/grafana  # Especifica la imagen Docker que se usará para el servicio Grafana (de la imagen oficial de Grafana en Docker Hub).

    ports:  # Configura el mapeo de puertos para Grafana.
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina local, permitiendo el acceso a la interfaz de Grafana.
