name: Crear release del juego

on:
  push:
    tags:
      - 'game-v*.*.*'  # Se ejecuta cuando se hace push de una etiqueta de versión (ej: game-v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout código
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Configura la versión de Python

      # Paso 3: Instalar PyInstaller
      - name: Instalar PyInstaller
        run: pip install pyinstaller  # Instala PyInstaller para empaquetar el script

      # Paso 4: Empaquetar el juego en un binario para Linux, incluyendo "words.txt"
      - name: Empaquetar el juego en binario para Linux
        working-directory: "Actividad 9"
        run: pyinstaller --onefile word-game/src/main.py --add-data "word-game/words.txt:word-game"

      # Paso 4.1: Verificar contenido de dist para confirmar el nombre del archivo generado
      - name: Verificar contenido de dist
        run: ls -R "Actividad 9/word-game/src/dist"

      # Paso 5: Crear release en GitHub con el binario generado
      - name: Crear release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "Actividad 9/word-game/src/dist/*"  # Publica cualquier archivo en el directorio "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utiliza el token de GitHub para autenticación
